package compiler;

import lexer.LexicalAnalyzer;
import parser.Parser;
import java.io.File;

/**
 * CMPU-331 (Compilers), Spring 2019
 *
 * This class wraps the rest of the compiler classes.
 * Initializes the passed in File to be read,
 * the lexical analyzer object, and the parser object
 *
 * @author jackiemun
 * @version
 */

public class Compiler {

    // private class data members

    private File File;
    private LexicalAnalyzer LexAn;
    private Parser Parser;

    /**
     * Constructor that takes an input file
     * @param file passed in file
     * @throws Exception
     */
    public Compiler(File file, boolean parseprint, boolean tviprint) throws Exception {
        this.File = file;
        this.LexAn = new LexicalAnalyzer(file);

        // this will call the parser

        this.Parser = new Parser(LexAn, parseprint, tviprint);
    }

    /**
     * Prints the  token stream generated by the lexical analyzer
     * (mainly used for testing purposes)
     * @throws Exception
     */
    public void PrintLexicalAnaylzer() throws Exception {
        while(!LexAn.IsEndOfFile()) {
            System.out.println(LexAn.ReadNewToken().TokenToString());
        }
    }
}
